### ISSUE TITLE
torch_tree missing

### ISSUE THREAD

**Issue by alexanderkoller** [facebookresearch/latent-treelstm#2]
Hi guys,

thanks for making the code available!

I'm trying to run the listops experiment, and am running into trouble in Step 4 of the instructions in the README, because Python can't find the module `torch_tree`. I can't find it on the Internet either. Is this a file that's missing in the repository?

The exact error message is below. Note that I have to run the script with `-m` because the syntax shown in the README won't work for me ("no module names 'utils'" because Python is looking for modules under the path of the script, not the current working directory).

Best,
Alexander.

```
koller@hilbert ~/D/w/latent-treelstm> python -m listops.ppo.train_ppo_model           (latent-treelstm) 
Traceback (most recent call last):
  File "/anaconda3/envs/latent-treelstm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/latent-treelstm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/koller/Documents/workspace/latent-treelstm/listops/ppo/train_ppo_model.py", line 17, in <module>
    from listops.models import PpoModel
  File "/Users/koller/Documents/workspace/latent-treelstm/listops/models/__init__.py", line 6, in <module>
    from listops.models.IdealTreeModel import IdealTreeModel
  File "/Users/koller/Documents/workspace/latent-treelstm/listops/models/IdealTreeModel.py", line 7, in <module>
    from modules import BinaryTreeLstmRnn
  File "/Users/koller/Documents/workspace/latent-treelstm/modules/__init__.py", line 9, in <module>
    from modules.BinaryTreeLstmRnn import BinaryTreeLstmRnn
  File "/Users/koller/Documents/workspace/latent-treelstm/modules/BinaryTreeLstmRnn.py", line 6, in <module>
    from torch_tree import BinaryTreeReducer
ModuleNotFoundError: No module named 'torch_tree'
```

**Comment by serhii-havrylov** [comment]
Hi Alexander,

Thank you for catching this. I forgot to remove some imports. [This](https://github.com/facebookresearch/latent-treelstm/pull/3) pull request should fix it.
Regarding "no module names 'utils'" issue, it is quite strange. I can run all those scripts from the project's directory, maybe try modifying PYTHONPATH variable: "PYTHONPATH=. python listops/ppo/train_ppo_model.py"

**Comment by alexanderkoller** [comment]
Great, that seems to work. Thanks for the quick response!

The issue can be closed once the PR has been integrated.

**Comment by alexanderkoller** [comment]
Also, the PYTHONPATH tip also worked.
